name: Lowlighter Metrics
on:
  # Cron schedule 
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: mpurdon 
          template: classic
          base: header, repositories
          plugin_isocalendar: yes
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: labels
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_rss: yes
          plugin_rss_source: https:/purdonmoi.com/blog/atom.xml
          plugin_rss_limit: 3

